### ISSUE TITLE
issue installing on symfony 4.1 / Sonata

### ISSUE THREAD

**Issue by acfi-network** [kunicmarko20/SonataImporterBundle#1]
The service "KunicMarko\SonataImporterBundle\Controller\ImportCRUDController" has a dependency on a non-existent service "KunicMarko\Importer\ImporterFactory.

PHP 7.2 - Symfony 4.1

Best regards

**Comment by kunicmarko20** [comment]
https://github.com/kunicmarko20/importer#symfony

You also need to add this bundle, this should be added in the readme here, my bad

**Comment by kunicmarko20** [comment]
https://github.com/kunicmarko20/SonataImporterBundle/blob/master/README.md#installation

Updated, does this resolve your issue?

**Comment by kunicmarko20** [comment]
@mathieudureisseix can this be closed?

**Comment by acfi-network** [comment]
Thanks for your answer :) it works perfectly ! Great job !
