### ISSUE TITLE
Import action breaks non-import admins

### ISSUE THREAD

**Issue by vstanchev** [kunicmarko20/SonataImporterBundle#2]
The method `AdminImportExtension::configureActionButtons` does not check if the current `$admin` implements  the `AdminWithImport` interface and alwasy adds the import action. This breaks admins for which an import does not exist with an exception similar to

> An exception has been thrown during the rendering of a template ("unable to find the route `admin.company.import`").

Proposed resolution is to check if `$admin` implements the import interface as follows:

```php
public function configureActionButtons(AdminInterface $admin, $list, $action, $object): array
    {
        if (!$admin instanceof AdminWithImport) {
            return $list;
        }

        $list['import']['template'] = $this->templates['action_button'];

        return $list;
    }
```

**Comment by kunicmarko20** [comment]
Sounds like a good solution, could you provide a pr for this? Tbh, didn't use this library in a while.
