### ISSUE TITLE
SonataImportConfiguration before not exists

### ISSUE THREAD

**Issue by grekpg** [kunicmarko20/SonataImporterBundle#7]
1 Why in sonata method before not exists. 
2 Is possible to get in 

`public function map(array $item, array $additionalData)`

item is 

```
 => array:2 [▼
    0 => "name"
    1 => "description"

```
i preffer - use first row as key names and get assoc array key=>value

here is my example file

name | description
-- | --
audi |  audi desc
BMW | desc bmw

is possble to configure it in this way ?

**Comment by kunicmarko20** [comment]
Unfortunately, this is not possible, because CsvReader is yielding information row by row as you can see [here](https://github.com/kunicmarko20/importer/blob/3dff24e540ad340f2841136d21e1e8104eb84f70/src/Reader/CsvReader.php#L24-L28).

What you can do is implement your own CsvReader that would replace how the data is processed.

**Comment by grekpg** [comment]
ok i someone want here is working example reader

```
namespace Mea\CoreBundle\Reader;

use Iterator;
use KunicMarko\Importer\Exception\InvalidArgumentException;
use KunicMarko\Importer\Reader\AbstractReader;

class MeaCsvReader extends AbstractReader
{

    public function getFormat(): string
    {
        return 'csv';
    }

    public function getItems(): Iterator
    {
        if (!$this->filename && !$this->content) {
            throw new InvalidArgumentException('Please provide a path to file or content from string.');
        }

        $file = $this->openFile();
        $keys = fgetcsv($file);
        while (!feof($file)) {
            $row = array_combine($keys, fgetcsv($file));
            yield $row;
        }

        fclose($file);
    }

    private function openFile()
    {
        if ($this->filename) {
            return fopen($this->filename, 'rb');
        }

        $file = fopen('php://temp', 'rb+');
        fwrite($file, $this->content);
        rewind($file);

        return $file;
    }

}
```

And here is service definition 

```
    Mea\CoreBundle\Reader\MeaCsvReader:
      decorates: KunicMarko\Importer\Reader\CsvReader
```
