### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by shaunthornburgh** [kunicmarko20/SonataImporterBundle#8]
Getting the following error when trying to install on Symfony 4.4:

The service "KunicMarko\SonataImporterBundle\Controller\ImportCRUDController" has a dependency on a non-existent service "KunicMarko\Importer\ImporterFactory".

**Comment by kunicmarko20** [comment]
Hey @shaunthornburgh,

Did you register both bundles as explained in the [readme](https://github.com/kunicmarko20/SonataImporterBundle#installation)?

```php
    KunicMarko\Importer\Bridge\Symfony\ImporterBundle::class => ['all' => true],
    KunicMarko\SonataImporterBundle\SonataImporterBundle::class => ['all' => true],
```

**Comment by shaunthornburgh** [comment]
Thanks for your reply, I am getting this error when running composer install so not getting past that step...
<img width="1233" alt="Screenshot 2020-09-02 at 14 22 06" src="https://user-images.githubusercontent.com/3660684/91990798-12521500-ed2a-11ea-96d5-d010f08dac06.png">

**Comment by kunicmarko20** [comment]
So as far as I can see, "Symfony flex" auto generates a recipe (I can see that from your output) and my assumption here is that it just enables `KunicMarko\SonataImporterBundle\SonataImporterBundle::class => ['all' => true],` but you are missing the other bundle, and that is why it is failing. I didn't see this before, I guess its a new flex feature? Will see if I can find some time to fix this, quickfix would be adding a custom recipe to https://github.com/symfony/recipes-contrib where it would be configured correctly.
