### ISSUE TITLE
Configuration - show or not

### ISSUE THREAD

**Issue by grekpg** [kunicmarko20/SonataImporterBundle#9]
I propose to add visible configuration - preferred method in admin - isImportEnabled() 

i can check user ROLE and then decide show import or not. Now is not easy remove import action because its add after admin configure routes / panel actions. 

thanks

**Comment by kunicmarko20** [comment]
Unfortunately I am not gonna be adding new features to this bundle because I barely maintain it, sorry, but if you have time, make a pull request and I will merge it.
